keycloak:
  realm: blog
  auth-server-url: http://localhost:8081/auth
  resource: article-service
  credentials:
    secret: bb792b2a-6836-4dfc-966c-7fac13a0d660
  bearer-only: true
  public-client: true
  principal-attribute: preferred_username


logging.level:
  org.springframework: DEBUG
  org.hibernate: DEBUG
  org.keycloak: TRACE