keycloak:
  realm: blog
  auth-server-url: http://sso-service:8443
  resource: comment-service
  credentials:
    secret: ${SSO_SECRET}
  bearer-only: true
  public-client: true
  principal-attribute: preferred_username

spring.data.mongodb:
  port: 27017
  host: comment-database
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  authentication-database: admin

logging.level:
  org.springframework: DEBUG
  org.hibernate: DEBUG
  org.keycloak: TRACE