server:
    port : 8080

services:
    article:
        url: http://localhost:8083
    comment:
        url: http://localhost:8082
    user:
        url: http://localhost:8084

keycloak:
    realm: blog
    auth-server-url: http://localhost:8081/auth
    resource: article-service
    credentials:
        secret: 748a2d12-28ef-40aa-8d38-cd8afb1e9c2d
    bearer-only: true
    public-client: true
    principal-attribute: preferred_username

logging.level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.keycloak: TRACE