services:
    article:
        url: http://article-service
    comment:
        url: http://comment-service
    user:
        url: http://user-service

keycloak:
    realm: blog
    auth-server-url: http://sso-service:8443
    resource: gateway-service
    credentials:
        secret: ${SSO_SECRET}
    bearer-only: true
    public-client: true
    principal-attribute: preferred_username