services:
    article:
        url: http://article-service
    comment:
        url: http://comment-service
    user:
        url: http://user-service

keycloak:
    realm: blog
    auth-server-url: ${SSO_ADDRESS}
    resource: gateway-service
    credentials:
        secret: ${SSO_SECRET}
    bearer-only: true
    public-client: true
    principal-attribute: preferred_username

server:
    ssl:
        key-store-type: PKCS12
        key-store: file:/mnt/certs/keystore.p12
        key-store-password: ${SSL_KEYSTORE_PASSWORD}
        key-alias: ${SSL_KEYSTORE_ALIAS}
        enabled: false
