services:
    article:
        url: http://article-service
    comment:
        url: http://comment-service
    user:
        url: http://user-service

keycloak:
    realm: blog
    auth-server-url: ${SSO_ADDRESS}
    resource: gateway-service
    credentials:
        secret: ${SSO_SECRET}
    bearer-only: true
    public-client: true
    principal-attribute: preferred_username


ssl:
    key-store:
        path: ${KEYSTORE_PATH}
        password: ${SSL_KEYSTORE_PASSWORD}
        alias: ${SSL_KEYSTORE_ALIAS}